FROM elasticsearch:latest

RUN  curl -o /tmp/ft.json https://raw.githubusercontent.com/fiunchinho/docker-filebeat/master/binary/filebeat.template.json
#RUN  curl -XPUT 'http://localhost:9200/_template/filebeat' -d@/tmp/ft.json 
